# Security Groups
sg_elb:
  - proto: tcp # T-Tower Wired
    from_port: 80
    to_port: 80
    cidr_ip: 203.236.3.0/24
  - proto: tcp # T-Tower Wifi
    from_port: 80
    to_port: 80
    cidr_ip: 203.236.9.0/24
  - proto: tcp # T-Tower Wired
    from_port: 443
    to_port: 443
    cidr_ip: 203.236.3.0/24
  - proto: tcp # T-Tower Wifi
    from_port: 443
    to_port: 443
    cidr_ip: 203.236.9.0/24
  - proto: tcp
    from_port: 443
    to_port: 443
    cidr_ip: 52.78.122.12/32
  - proto: tcp
    from_port: 80
    to_port: 80
    cidr_ip: 52.78.10.248/32
  - proto: tcp
    from_port: 443
    to_port: 443
    cidr_ip: 52.78.10.248/32
  - proto: icmp
    from_port: 8
    to_port: -1
    cidr_ip: 52.78.10.248/32
  - proto: tcp # nGrinder.agent
    from_port: 443
    to_port: 443
    cidr_ip: 52.78.153.132/32
  - proto: tcp # nGrinder.agent
    from_port: 443
    to_port: 443
    cidr_ip: 52.78.153.228/32
  - proto: tcp # nGrinder.agent
    from_port: 443
    to_port: 443
    cidr_ip: 52.78.179.29/32
  - proto: tcp # nGrinder.agent
    from_port: 443
    to_port: 443
    cidr_ip: 52.79.80.111/32
  - proto: tcp # VPN EIP
    from_port: 80
    to_port: 80
    cidr_ip: 52.79.50.145/32
  - proto: tcp # VPN EIP
    from_port: 443
    to_port: 443
    cidr_ip: 52.79.50.145/32

sg_instance:
  - proto: tcp
    from_port: 2022
    to_port: 2022
    group_name: "{{ tag_env }}-jumphost"
  - proto: tcp
    from_port: 2080
    to_port: 2080
    group_name: "{{ tag_name }}-elb"
  - proto: tcp
    from_port: 9000
    to_port: 9000
    group_name: "{{ tag_name }}-elb"
  - proto: tcp
    from_port: 9000
    to_port: 9000
    cidr_ip: 10.10.90.58/32
  - proto: tcp
    from_port: 9000
    to_port: 9000
    group_name: stg-qa
