---
# file: roles/aws/ami/tasks/main.yml
- include_vars: "{{ tag_name }}.yml"

- name: find ec2 instance
  ec2:
    image: "{{ image }}"
    region: "{{ region }}"
    vpc_subnet_id: "{{ subnet_id }}"
    instance_tags: "{{ tags }}"
    count_tag: "{{ tags }}"
    exact_count: "{{ vm_per_subnet }}"
  register: ec2

- name: create an instance in ami
  ec2_ami:
    region: "{{ region }}"
    instance_id: "{{ item.id }}"
    wait: no
    no_reboot: yes
    name: "{{ tag_name }}-{{ version }}"
    tags: 
      Name: "{{ tag_name }}-{{ version }}"
  register: ami
  with_items: "{{ ec2.tagged_instances }}"
  ignore_errors: yes

- name: Rotation ami - find ami
  ec2_ami_find:
    region: "{{ region }}"
    name: "{{ tag_name }}-*"
    sort: creationDate
    sort_order: descending
  register: ami_find

- name: terminate an instance in old ami
  ec2_ami:
    region: "{{ region }}"
    image_id: "{{ item.ami_id }}"
    delete_snapshot: yes
    state: "absent"
  with_items: "{{ ami_find.results[rotation:(ami_find.results|length)] }}"
