---
# file: stg-ex-api.yml

- name: AWS provisioning
  hosts: localhost
  gather_facts: False
  vars:
    tag_name: stg-ex-api
    lcver: 2017033001 # laucher config version
    instance_type: t2.large
    instance_role: api-role
    elb_conn_drain_tmout: 10
  roles:
    # tag_name : string, tag name of dependency security group
    - { role: aws/sg, tag_name: "stg-ex-web" }
    - { role: aws/sg }
    - { role: aws/ext-asg-elb } # For Nginx Gateway
    - { role: aws/int-asg-elb }
    # Autoscaling notification is generated when you create a sns
    - { role: aws/sns, sns: "{{ auto_scaling_sns }}" }
    # target : string, deploy target app or web
    # scheduled : boolean, Auto scal schedule
    - { role: aws/auto-scale, target: app, scheduled: false }

- name: Configure instance(s)
  hosts: tag_Name_stg-ex-api
  gather_facts: False
  serial: 1
  vars:
    tag_name: stg-ex-api
    domain: stg-ex-api.sktvl.com
    awslogs: {
      target: [ catalina, api, inicis ] # target : array, values = [ catalina, admin, api, batch, nodejs, inicis ], log target parameter
    }
    inicis_mid: skthidden1
  roles:
    - { role: modules/nginx }
    - { role: modules/java }
    # enable_scouter : boolean, Enable Scouter Agent, true=regist scouter angent, false=skip
    - { role: modules/tomcat, enable_scouter: true }
    - { role: modules/awslogs }
    - { role: modules/scouter-agent, scouter_server: 10.14.20.203 } # scouter_server : ip, scouter server ip
    - { role: modules/scouter-host, scouter_server: 10.14.20.203 } # scouter_server : ip, scouter server ip
    - { role: wrapper-node }
