---
# file: stg-scouter.yml

- name: AWS provisioning
  hosts: localhost
  gather_facts: False
  vars:
    tag_name: stg-scouter
    instance_type: t2.medium
    instance_role: cloudwatch-logs-role
    termination_protection: yes
    vm_per_subnet: 1
  roles:
    - { role: aws/sg }
    - { role: aws/ec2, subnet_id: "{{ subnet20 }}" }
    # Auto Recovery notification is generated when you create a sns
    - { role: aws/sns, sns: "{{ auto_recovery_sns }}" }
    - { role: aws/auto-recovery }

- name: Configure instance(s)
  hosts: tag_Name_stg-scouter
  gather_facts: False
  serial: 1
  vars:
    tag_name: stg-scouter
    domain: localhost
  roles:
    - { role: modules/java }
    - { role: wrapper-node }
