---
# roles/aws/eip/tasks/main.yml
- include_vars: "{{ tag_name }}.yml"

- name: allocate a new elastic IP and associate it with an instance
  ec2_eip:
    device_id: "{{ item.id }}"
    region: "{{ region }}"
  with_items: "{{ ec2.instances }}"
  