---
# file: roles/modules/elasticsearch/tasks/configure.yml
- include_vars: "{{ tag_name }}.yml"

- name: Install Devel Packages
  yum: pkg="{{ item }}" state=installed
  with_items:
    - elasticsearch
    - jdk-1.8.0-oracle

- stat: path=/usr/share/elasticsearch/plugins/kopf
  register: kopf

- name: kopf plugin install
  shell: /usr/share/elasticsearch/bin/plugin install lmenezes/elasticsearch-kopf/master
  when: not kopf.stat.exists

- stat: path=/etc/elasticsearch/config
  register: config

- name: analysis-seunjeon plugin copy
  copy: src=config dest=/etc/elasticsearch/

- name: analysis-seunjeon plugin copy
  copy: src=analysis-seunjeon dest=/usr/share/elasticsearch/plugins/
  notify: restart elasticsearch

- name: copy sysconfig elasticsearch
  template: src=elasticsearch.j2 dest=/etc/sysconfig/elasticsearch owner=root group=root mode=644
  notify: restart elasticsearch

- name: set elasticsearch.yml
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=root group=root mode=644
  notify: restart elasticsearch
