---
# file: roles/deploy_spring_boot/tasks/main.yml
- include_vars: "{{ tag_name }}.yml"

- stat: path=/skt/repo/{{ tag_env }}/{{ tag_name }}/new/ROOT.jar
  delegate_to: jenkins.sktvl.com
  register: rs

- name: stop "spring-boot"
  service: name="spring-boot" state=stopped
  when: rs.stat.exists

- name: deploy webapps
  synchronize: src=/skt/repo/{{ tag_env }}/{{ tag_name }}/new/ROOT.jar dest=/skt/was/apps/instance01/webapps/ROOT.jar
  delegate_to: jenkins.sktvl.com
  when: rs.stat.exists

- name: start "spring-boot"
  service: name="spring-boot" state=started
  when: rs.stat.exists

- name: wait for "spring-boot" restart
  wait_for: port=9000 host={{ inventory_hostname }} delay=30
  when: rs.stat.exists

- name: check siteup.html is available
  uri: url=http://{{ inventory_hostname }}:9000{{ siteup_url }}
  when: rs.stat.exists
