---
# file: prd-ex-batch.yml

- name: AWS provisioning
  hosts: localhost
  gather_facts: False
  vars:
    tag_name: prd-ex-batch
    instance_type: c4.xlarge
    instance_role: api-role
    termination_protection: yes
    elb_conn_drain_tmout: 10
    vm_per_subnet: 1
  roles:
    - { role: aws/sg }
    # Auto Recovery notification is generated when you create a sns
    - { role: aws/sns, sns: "{{ auto_recovery_sns }}" }
    - { role: aws/ec2, subnet_id: "{{ subnet20 }}" }
    
- name: Configure instance(s)
  hosts: tag_Name_prd-ex-batch
  gather_facts: False
  serial: 1
  vars:
    tag_name: prd-ex-batch
    jenkins_secret: "83824cc7f45b95ba489d133a66ae253092f703d8639912f370ca7fa6991116f5"
    awslogs: {
      target: [ batch ] # target : array, values = [ catalina, admin, api, batch, nodejs ], log target parameter
    }
  roles:
    - { role: aws/cloudwatch-alarm }
    - { role: modules/java }
    - { role: modules/jenkins-slave }
    - { role: modules/awslogs }
    - { role: wrapper-node }
