sg_instance:
  - proto: tcp
    from_port: 80
    to_port: 80
    cidr_ip: 0.0.0.0/0
  - proto: tcp
    from_port: 443
    to_port: 443
    cidr_ip: 0.0.0.0/0
  - proto: icmp # Ping Monitoring
    from_port: 8
    to_port: -1
    cidr_ip: 52.78.10.248/32
