# Elasticsearch parameter
cluster_name: hidden-es
node_name: es-{{ inventory_hostname }}
http_port: 11200
tcp_port: 11300
number_of_shards: 5
number_of_replicas: 1
minimum_master_nodes: 2
node_initial_primaries_recoveries: 5
node_concurrent_recoveries: 4
concurrent_streams: 5
recover_after_nodes: 1
expected_nodes: 2

# Security Groups
sg_instance:
  - proto: tcp
    from_port: 11200
    to_port: 11200
    group_name: "prd-ex-search-api"
  - proto: tcp
    from_port: 11300
    to_port: 11300
    group_name: "prd-ex-search-api"
  - proto: tcp
    from_port: 11200
    to_port: 11200
    group_name: "preprd-ex-search-api"
  - proto: tcp
    from_port: 11300
    to_port: 11300
    group_name: "preprd-ex-search-api"
  - proto: tcp
    from_port: 11200
    to_port: 11200
    group_name: "prd-logstash"
  - proto: tcp
    from_port: 11200
    to_port: 11200
    group_name: "prd-es"
  - proto: tcp
    from_port: 11200
    to_port: 11200
    group_name: "prd-kibana"
  - proto: tcp
    from_port: 11300
    to_port: 11300
    group_name: "prd-es"
  - proto: tcp
    from_port: 11300
    to_port: 11300
    group_name: "prd-ex-batch"
  # VPN
  - proto: tcp
    from_port: 11200
    to_port: 11200
    cidr_ip: 10.10.90.218/32
  - proto: tcp
    from_port: 11300
    to_port: 11300
    cidr_ip: 10.10.90.218/32
  # Jenkins
  - proto: tcp
    from_port: 11200
    to_port: 11200
    cidr_ip: 10.10.90.58/32
  # Jenkins
  - proto: tcp
    from_port: 11300
    to_port: 11300
    cidr_ip: 10.10.90.58/32
