---
# file: dev-ex-batch.yml

- name: AWS provisioning
  hosts: localhost
  gather_facts: False
  vars:
    tag_name: dev-ex-batch
    instance_type: c4.xlarge
    instance_role: api-role
    termination_protection: yes
    elb_conn_drain_tmout: 10
    vm_per_subnet: 1
  roles:
    - { role: aws/sg }
    - { role: aws/ec2, subnet_id: "{{ subnet20 }}" }

- name: Configure instance(s)
  hosts: tag_Name_dev-ex-batch
  gather_facts: False
  serial: 1
  vars:
    tag_name: dev-ex-batch
    jenkins_secret: "b1893f200d9cc22ae43667f270d2c9bf4410a0dbd9f96cd8240d12ca00f7d610"
  roles:
    - { role: modules/java }
    - { role: modules/jenkins-slave }
    - { role: modules/spring-boot }
    - { role: wrapper-node }
