---
# file: dev-ex-recmd.yml

- name: AWS provisioning
  hosts: localhost
  gather_facts: False
  vars:
    tag_name: dev-ex-recmd
    instance_type: t2.medium
    instance_role: api-role
    termination_protection: yes
    vm_per_subnet: 1
  roles:
    # tag_name : string, tag name of dependency security group
    - { role: aws/sg }
    - { role: aws/ec2, subnet_id: "{{ subnet20 }}" }

- name: Configure instance(s)
  hosts: tag_Name_dev-ex-recmd
  gather_facts: False
  serial: 1
  vars:
    tag_name: dev-ex-recmd
    jenkins_secret: "219dd4110b24ff6076b1721cec9aff72257acf9bdc747ae97d8b867ffcaa8946"
  roles:
    - { role: modules/java }
    - { role: modules/jenkins-slave }
    - { role: wrapper-node }
