---
# file: dev-ex-thumbor.yml

- name: AWS provisioning
  hosts: localhost
  gather_facts: False
  vars:
    tag_name: dev-ex-thumbor
    instance_type: t2.micro
    instance_role: api-role
    termination_protection: yes
    vm_per_subnet: 1
    elb_conn_drain_tmout: 10
  roles:
    - { role: aws/sg }
    - { role: aws/ec2, subnet_id: "{{ subnet20 }}" }
    - { role: aws/ext-elb }

- name: Configure instance(s)
  hosts: tag_Name_dev-ex-thumbor
  gather_facts: False
  serial: 1
  vars:
    tag_name: dev-ex-thumbor
    domain: thumbor-ex.sktvl.net
  roles:
    - { role: modules/nginx }
    - { role: wrapper-node }
