---
# file: group_vars/all.yml

# Environment Variable Set
tag_env: prd

# Set Network Params
vpc_id: vpc-e1a51a88
region: ap-northeast-2
subnet10: subnet-ef67df86
subnet20: subnet-b758e0de
subnet30: subnet-9d58e0f4
subnet90: subnet-8567dfec
subnet110: subnet-2100f86c
subnet120: subnet-3e01f973
subnet130: subnet-3101f97c
subnet190: subnet-df00f892

# Set Instance Params
keypair: team2_prd
