---
# file: roles/aws/ec2/tasks/ec2.yml
- include_vars: "group_vars/{{ lookup('env', 'AWS_PROFILE') }}.yml"

- name: Find Current AWS Autoscaling Groups
  ec2_asg:
    name: "{{ tag_name }}"
    region: "{{ region }}"
  register: asg

- name: Find Current AWS Autoscaling Launch Configurations
  ec2_lc:
    name: "{{ asg.launch_config_name }}"
    region: "{{ region }}"
  register: lc

- name: create an instance in ec2
  ec2:
    key_name: "{{ keypair }}"
    group: [ "common", "{{ tag_name }}" ]
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    wait: true
    region: "{{ region }}"
    vpc_subnet_id: "{{ subnet_id }}"
    termination_protection: no
    instance_tags:
        Name: "{{ tag_name }}-{{ lcver }}"
        Env: "{{ tag_env }}"
    count_tag:
        Name: "{{ tag_name }}-{{ lcver }}"
        Env: "{{ tag_env }}"
    exact_count: "{{ vm_per_subnet }}"
    user_data: "{{ userdata }}"
  register: ec2

- name: Wait for SSH to come up
  wait_for: host="{{ item.private_dns_name }}" port=2022 delay=30 timeout=180 state=started
  with_items: "{{ ec2.instances }}"

- name: Add new instance to host group
  add_host: hostname="{{ item.private_ip }}" groupname=launched tag_name="{{ tag_name }}"
  with_items: "{{ ec2.instances }}"
