---
# file: prd-bi-jumphost.yml

- include: common.yml

- name: AWS jumphost instance provisioning
  hosts: localhost
  gather_facts: False
  vars:
    tag_name: prd-bi-jumphost
    instance_type: t2.micro
    instance_role: cloudwatch-logs-role
    termination_protection: yes
    vm_per_subnet: 1 
  roles:
    - { role: aws/sg }
    - { role: aws/ec2, subnet_id: "{{ subnet20 }}" }

- name: Configure instance(s)
  hosts: tag_Name_prd-bi-jumphost
  gather_facts: False
  serial: 1
  vars:
    tag_name: prd-bi-jumphost
    domain: localhost
  roles:
    - { role: modules/jumphost }
    #- { role: wrapper-node }
