# Security Group
sg_elb:
  - proto: tcp
    from_port: 443
    to_port: 443
    cidr_ip: 210.211.88.0/24
  - proto: tcp
    from_port: 443
    to_port: 443
    cidr_ip: 203.236.3.0/24
  - proto: tcp
    from_port: 443
    to_port: 443
    cidr_ip: 52.78.10.248/32
  - proto: tcp # VPN EIP
    from_port: 443
    to_port: 443
    cidr_ip: 52.79.50.145/32
  - proto: icmp # Ping Monitoring
    from_port: 8
    to_port: -1
    cidr_ip: 52.78.10.248/32

sg_internal_elb:
  - proto: tcp
    from_port: 9000
    to_port: 9000
    group_name: "prd-ex-web"

sg_instance:
  - proto: tcp
    from_port: 9000
    to_port: 9000
    group_name: "{{ tag_name }}-elb"
  - proto: tcp
    from_port: 9000
    to_port: 9000
    group_name: "{{ tag_name }}-internal-elb"
  - proto: tcp # Jenkins health check
    from_port: 9000
    to_port: 9000
    cidr_ip: 10.10.90.58/32
