---
# file: sg.yml
# ex ansible-playbook pmin-sg.yml -e "tag_name=prd-rds"

- name: Service PM IN Security Group
  hosts: localhost
  vars_files:
    - "../{{ lookup('env', 'AWS_PROFILE') }}/group_vars/all.yml"
  roles:
    - { role: pm/in/sg }
