# Security Groups
sg_instance:
  - proto: tcp
    from_port: 2022
    to_port: 2022
    group_name: "{{ tag_env }}-jumphost"
  - proto: all
    cidr_ip: 10.15.0.0/16
  # VPN
  - proto: tcp
    from_port: 9200
    to_port: 9200
    cidr_ip: 10.10.90.218/32
  - proto: tcp
    from_port: 9300
    to_port: 9300
    cidr_ip: 10.10.90.218/32
  # VPN to Kibana
  - proto: tcp
    from_port: 5601
    to_port: 5601
    cidr_ip: 10.10.90.218/32
  # Jenkins
  - proto: tcp
    from_port: 9200
    to_port: 9200
    cidr_ip: 10.10.90.58/32
  # Jenkins
  - proto: tcp
    from_port: 9300
    to_port: 9300
    cidr_ip: 10.10.90.58/32
    
