# Middleware Siteup
siteup_url: /search/siteup.html

# Local Internal ELB Listeners, Health Check
int_elb_listeners:
  - protocol: http # API Internal
    load_balancer_port: 9000
    instance_protocol: http
    instance_port: 9000

health_check_int_elb: {
  ping_protocol: http,
  ping_port: 9000,
  ping_path: "{{ siteup_url }}",
  response_timeout: 5,
  interval: 10,
  unhealthy_threshold: 2,
  healthy_threshold: 2
}

# Security Groups
sg_internal_elb:
  - proto: tcp
    from_port: 9000
    to_port: 9000
    cidr_ip: 10.15.0.0/16

sg_instance:
  - proto: tcp
    from_port: 2022
    to_port: 2022
    group_name: "{{ tag_env }}-jumphost"
  - proto: all
    cidr_ip: 10.15.0.0/16
  - proto: all
    group_name: "{{ tag_name }}-internal-elb"
