# Elasticsearch parameter
cluster_name: hidden-recmd-es
node_name: es-{{ inventory_hostname }}
http_port: 11200
tcp_port: 11300
number_of_shards: 5
number_of_replicas: 0
minimum_master_nodes: 1
node_initial_primaries_recoveries: 5
node_concurrent_recoveries: 4
concurrent_streams: 5
recover_after_nodes: 1
expected_nodes: 1

# Security Groups
sg_instance:
  - proto: tcp
    from_port: 2022
    to_port: 2022
    group_name: "{{ tag_env }}-jumphost"
  - proto: all
    cidr_ip: 10.15.0.0/16
  # VPN
  - proto: tcp
    from_port: 11200
    to_port: 11200
    cidr_ip: 10.10.90.218/32
  - proto: tcp
    from_port: 11300
    to_port: 11300
    cidr_ip: 10.10.90.218/32
  # VPN to Kibana
  - proto: tcp
    from_port: 5608
    to_port: 5608
    cidr_ip: 10.10.90.218/32
  # Jenkins
  - proto: tcp
    from_port: 11200
    to_port: 11200
    cidr_ip: 10.10.90.58/32
  # Jenkins
  - proto: tcp
    from_port: 11300
    to_port: 11300
    cidr_ip: 10.10.90.58/32

