# Local External ELB Listeners, Health Check For Nginx
ext_elb_listeners:
  - protocol: https
    load_balancer_port: 443
    instance_protocol: http
    instance_port: 2080
    ssl_certificate_id: "{{ ssl_certificate_id }}"
  - protocol: http
    load_balancer_port: 80
    instance_protocol: http
    instance_port: 2080
  - protocol: https
    load_balancer_port: 8443
    instance_protocol: http
    instance_port: 9001
    ssl_certificate_id: "{{ ssl_certificate_id }}"

health_check_ext_elb: {
  ping_protocol: http,
  ping_port: 2080,
  ping_path: "{{ siteup_url }}",
  response_timeout: 5,
  interval: 10,
  unhealthy_threshold: 2,
  healthy_threshold: 2
}

# Local Internal ELB Listeners, Health Check
int_elb_listeners:
  - protocol: http # Nginx Internal
    load_balancer_port: 80
    instance_protocol: http
    instance_port: 2080
  - protocol: http # API Internal
    load_balancer_port: 9000
    instance_protocol: http
    instance_port: 9000

health_check_int_elb: {
  ping_protocol: http,
  ping_port: 2080,
  ping_path: "{{ siteup_url }}",
  response_timeout: 5,
  interval: 10,
  unhealthy_threshold: 2,
  healthy_threshold: 2
}

# Security Groups
sg_elb:
  - proto: tcp
    from_port: 80
    to_port: 80
    group_name: "dev-ex-apiapp"
  - proto: tcp
    from_port: 80
    to_port: 80
    group_name: "dev-ex-web"
  - proto: tcp
    from_port: 80
    to_port: 80
    group_name: "dev-fe-web"
  - proto: tcp # T-Tower Wired
    from_port: 443
    to_port: 443
    cidr_ip: 203.236.3.0/24
  - proto: tcp # T-Tower Wifi
    from_port: 443
    to_port: 443
    cidr_ip: 203.236.9.0/24
  - proto: tcp # T-Tower Wired
    from_port: 8443
    to_port: 8443
    cidr_ip: 203.236.3.0/24
  - proto: tcp # T-Tower Wifi
    from_port: 8443
    to_port: 8443
    cidr_ip: 203.236.9.0/24
  - proto: tcp
    from_port: 443
    to_port: 443
    cidr_ip: 52.78.10.248/32
  - proto: tcp
    from_port: 8443
    to_port: 8443
    cidr_ip: 52.78.10.248/32
  - proto: tcp # VPN EIP
    from_port: 80
    to_port: 80
    cidr_ip: 52.79.50.145/32
  - proto: tcp # VPN EIP
    from_port: 443
    to_port: 443
    cidr_ip: 52.79.50.145/32
  - proto: tcp # VPN EIP
    from_port: 8443
    to_port: 8443
    cidr_ip: 52.79.50.145/32
  - proto: icmp
    from_port: 8
    to_port: -1
    cidr_ip: 52.78.10.248/32

sg_internal_elb:
  - proto: tcp
    from_port: 80
    to_port: 80
    cidr_ip: 10.0.0.0/8

sg_instance:
  - proto: tcp
    from_port: 2022
    to_port: 2022
    group_name: "{{ tag_env }}-jumphost"
  - proto: all
    cidr_ip: 10.15.0.0/16
  - proto: all
    group_name: "{{ tag_name }}-elb"
  - proto: all
    group_name: "{{ tag_name }}-internal-elb"
