# Security Groups
sg_instance:
  - proto: tcp
    from_port: 5306
    to_port: 5306
    cidr_ip: 10.15.0.0/16
  # VPN
  - proto: tcp
    from_port: 5306
    to_port: 5306
    cidr_ip: 10.10.90.218/32
  # Jenkins
  - proto: tcp
    from_port: 5306
    to_port: 5306
    cidr_ip: 10.10.90.58/32
  # DBA instance
  - proto: tcp
    from_port: 5306
    to_port: 5306
    cidr_ip: 10.10.10.243/32
  # DBA VPN
  - proto: tcp
    from_port: 5306
    to_port: 5306
    cidr_ip: 10.10.190.229/32
