# ELB Listeners
elb_listeners:
  - protocol: http
    load_balancer_port: 80
    instance_protocol: http
    instance_port: 2080
  - protocol: https
    load_balancer_port: 443
    instance_protocol: http
    instance_port: 2080
    ssl_certificate_id: "{{ ssl_certificate_id }}"

# Security Groups
sg_elb:
  - proto: tcp
    from_port: 80
    to_port: 80
    cidr_ip: 203.236.3.0/24
  - proto: tcp
    from_port: 443
    to_port: 443
    cidr_ip: 203.236.3.0/24
  - proto: tcp # VPN EIP
    from_port: 80
    to_port: 80
    cidr_ip: 52.79.50.145/32
  - proto: tcp # VPN EIP
    from_port: 443
    to_port: 443
    cidr_ip: 52.79.50.145/32

sg_instance:
  - proto: all
    cidr_ip: 10.11.0.0/16
  - proto: all
    group_name: "{{ tag_name }}-elb"
